/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatroomtes2;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.math.*;
import java.util.Scanner;
import javax.swing.JOptionPane;

public class LogIn extends javax.swing.JFrame {

    File filename = new File("LogIns.txt"); //filename for usernames and passwords
    boolean empty = false; //checks for empty fields
    String name; //username

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        setCaptcha(); //calls this when log in is made to make a captcha
    }

    public String getName() { //takes username
        name = userTxf.getText(); 
        return name;
    }

    public void setName() { //gives name a value
        name = userTxf.getText(); 

    }

    //sets the captcha in the gui so the user can see it, it is a randomly generated number
    public void setCaptcha() {
        double captchaNum;
        captchaNum = Math.random() * 899 + 100;
        int cap = (int) captchaNum;
        captchaTxa.setText(cap + "");
    }

    //this runs when log in hit and checks to see if the users login exists and allows them to log in
    public boolean findUser() {
        String name1 = userTxf.getText();
        String password1 = passTxf.getText();
        if (name1.length() < 1 || password1.length() < 1) {
            empty = true;
            System.out.println(empty);
            JOptionPane.showMessageDialog(rootPane, "Username or Password fields blank");
            return false;
        }
        String nameF;
        String passwordF;
        boolean right = false;
        try {
            Scanner sc = new Scanner(filename);

            while (sc.hasNextLine()) {
                nameF = sc.nextLine();
                System.out.println(nameF);
                passwordF = sc.nextLine();
                System.out.println(passwordF);
                if (nameF.equals(name1)) {
                    if (passwordF.equals(password1)) {
                        right = true;
                        break;
                    } else {
                        right = false;
                        break;
                    }
                } else {
                    right = false;

                }
            }
            sc.close();

        } catch (Exception e) {
            System.out.println("e");
        }
        return right;
    }

    //this is to register the user it checks if the log in already exists and then write to textfile
    public void signUp() {
        try {

            PrintWriter pw = new PrintWriter(new FileWriter(filename, true)); 
            String user1 = userTxf.getText();
            String pass1 = passTxf.getText();
            if (user1.length() < 1 || pass1.length() < 1) { //checks if the fields are empty
                empty = true;
                System.out.println(empty);
                JOptionPane.showMessageDialog(rootPane, "Username or Password fields blank");
            } else if (findUser()) { //checks if username and password exist
                JOptionPane.showMessageDialog(rootPane, "Username already exists");

            } else { //writes
                pw.println(user1);
                pw.println(pass1);
                JOptionPane.showMessageDialog(rootPane, "Registered");
            }
            pw.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public boolean checkCaptcha() { //checks if the user entered the right captcha
        String check = captchaTxa.getText();
        String userCheck = captchaTxf.getText();
        boolean right1 = true;
        if (check.equals(userCheck)) {
            right1 = true;
        } else {
            right1 = false;
        }
        return right1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logBtn = new javax.swing.JButton();
        regBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userTxf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        captchaTxf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        captchaTxa = new javax.swing.JTextArea();
        passTxf = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(182, 209, 224));

        logBtn.setText("Log in");
        logBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBtnActionPerformed(evt);
            }
        });

        regBtn.setText("Register");
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Username:");

        jLabel1.setText("Password:");

        jLabel3.setText("Enter Captcha:");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        captchaTxa.setEditable(false);
        captchaTxa.setColumns(20);
        captchaTxa.setFont(new java.awt.Font("Ubuntu", 0, 60)); // NOI18N
        captchaTxa.setForeground(new java.awt.Color(50, 238, 21));
        captchaTxa.setLineWrap(true);
        captchaTxa.setRows(5);
        jScrollPane1.setViewportView(captchaTxa);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(userTxf, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(passTxf))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(captchaTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(captchaTxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userTxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passTxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(regBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logBtn)
                    .addComponent(regBtn))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBtnActionPerformed
        if (checkCaptcha()) { //checks if the captcha is correct after clicking the log in button
            if (findUser()) { 
                JOptionPane.showMessageDialog(rootPane, "Welcome");
                setName();
                this.setVisible(false);
                Client c = new Client(getName()); //makes a new client after log in process is finished
                c.clientRun();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Log in incorrect");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Captcha code is incorrect");
        }
    }//GEN-LAST:event_logBtnActionPerformed

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        if (checkCaptcha()) { //checks if the captcha is correct after clicking the log in button
            if (!empty) {
                signUp();
                setName();
                this.setVisible(false);
                Client c = new Client(getName());
                c.clientRun(); //makes a new client after log in process is finished
            } else {
                signUp();
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Captcha code is incorrect");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_regBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea captchaTxa;
    private javax.swing.JTextField captchaTxf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logBtn;
    private javax.swing.JPasswordField passTxf;
    private javax.swing.JButton regBtn;
    private javax.swing.JTextField userTxf;
    // End of variables declaration//GEN-END:variables
}
